### PR TITLE
Remove `PaginatorInterface::getSort()`

### PR DESCRIPTION
**Pull request by vjik**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  | -

### CODE REVIEW

**Comment by xepozz** [comment]
Any reasons for these changes?

**Comment by vjik** [comment]
> Any reasons for these changes?

Receiving sort object from pagination looks illogical. Exist data provider for it.

**Comment by roxblnfk** [comment]
Did you test an impact of the change?

**Comment by vjik** [comment]
> Did you test an impact of the change?

Seems, it's not used anywhere.

**Comment by roxblnfk** [comment]
> > Any reasons for these changes?
> 
> Receiving sort object from pagination looks illogical. Exist data provider for it.

What is the `data provider`? `DataReader`? You can't get it from the Paginator.

**Comment by vjik** [comment]
> What is the `data provider`? `DataReader`?

Oh, data reader, of course. 

> You can't get it from the PaginatorInterface.

Yes. I think, it's not need.

**Comment by roxblnfk** [comment]
> > You can't get it from the PaginatorInterface.
> 
> Yes. I consider, it's not need.

Why do you think so? Sorting is an important part of the any paginator.
Limit (`getPageSize`) and Sort options are common things for the both paginators.

**Comment by vjik** [comment]
Close PR. I need to think about the package more globally :)

**Pull request closed without merging**
